Tracker:AddLocations("locations/Battle Collosseum.json")
Tracker:AddLocations("locations/Death Mountain.json")
Tracker:AddLocations("locations/Eternal War.json")
Tracker:AddLocations("locations/Everhood 1.json")
Tracker:AddLocations("locations/Hillbert Hotel.json")
Tracker:AddLocations("locations/Home Town.json")
Tracker:AddLocations("locations/Infinity Hub.json")
Tracker:AddLocations("locations/Marzian Era 0.json")
Tracker:AddLocations("locations/Marzian Era 3000.json")
Tracker:AddLocations("locations/Marzian Era 4000.json")
Tracker:AddLocations("locations/Mushroom Bureau.json")
Tracker:AddLocations("locations/Neon Jungle.json")
Tracker:AddLocations("locations/Pandemonium.json")
Tracker:AddLocations("locations/Riley's Fortress.json")
Tracker:AddLocations("locations/Smega Console.json")
Tracker:AddLocations("locations/Lab.json")
Tracker:AddLocations("locations/Cosmic Hub.json")